### ISSUE TITLE
怎么在其他ide中使用魔兽的lua引擎呢

### ISSUE THREAD

**Issue by PhoenixZeng** [actboy168/jass2lua#3]
比如获取到内置库

**Comment by actboy168** [comment]
我不懂你的意思

**Comment by PhoenixZeng** [comment]
在一些ide中具有语法提示,代码完成等功能,他可以获取到被require的库下面的所有函数进行提示
而我们比如经常会cj = require "jass.common" japi=require "jass.japi"之类的.这里就不知道从哪require.也没法获取到内部的函数进行提示,有些ide甚至会报错说require了一个未知文件.
另外:我尝试按照"MoeHero-master"中所说的进行操作.但是我下载MoeHero-master后没办法打包地图,会提示
`找不到 C:\Users\Phoenix\Desktop\w3x\MoeHero-master\map\lua\currentpath.lua
C:\Users\Phoenix\Desktop\w3x\MoeHero-master\tools\bin\lua.exe: C:\Users\Phoenix\Desktop\w3x\MoeHero-master\tools\make.lua:8: module 'utility' not found:`

**Comment by actboy168** [comment]
你的IDE如何能识别内置库，并不是我的问题，而是你的IDE的问题

**Comment by PhoenixZeng** [comment]
我其实就是想知道内置库在哪个dll里面?我应该如何加载?
还有就是你的MoeHero-master这个项目打包报错该如何解决

**Comment by actboy168** [comment]
如何加载，不同的IDE方法自然不同，我并不知道你使用的IDE所以无法给你任何答案。况且我没有义务教你使用你的IDE。如果你还是无法理解我上诉说的东西，那我就明确地说，**无法在IDE里加载内置库**。

此外，不要把issues当成im聊天工具。
1. 一个iusse讨论一个问题，如果你有其他问题请另开iusse。
2. 不要在这里讨论和本项目无关的问题。

**Comment by PhoenixZeng** [comment]
抱歉,我平时上github比较少,所以不是很清楚这里的用法.不好意思.
我所使用的工具是IntelliJ IDEA+EmmyLua插件.如果不能三言两语就说清楚如何加载的话,那就算了.反正也不影响导入地图后的使用.
最后还是谢谢您在百忙之中抽空给出回复.谢谢
