### ISSUE TITLE
关于lua调用jass自定义函数

### ISSUE THREAD

**Issue by bamboo98** [actboy168/jass2lua#5]
请问要在jass里声明code类型的全局变量并且赋值应该怎样做
以及赋值之后要怎样在lua层调用呢,例子只给了jass调用lua的函数呢....
要是能再给个简单几行的调用例子就太感谢了...

**Comment by bamboo98** [comment]
关于这个问题我在网上搜了好多教程也没找到有定义code类型的操作,只能找到code类作为参数传入函数的例子...完全不知道怎么声明

**Comment by sumneko** [comment]
lua不能直接调用jass中的自定义函数。在jass中将自定义函数保存在code变量中后，lua可以使用jass的api操作变量。

**Comment by bamboo98** [comment]
请问jass中将自定义函数保存在code变量这个操作具体应该怎样实现?网上找了一晚上也没找到有任何关于声明code变量的例子....
还有lua调用的jass的api是哪一个呢

**Comment by sumneko** [comment]
就和其他变量一样，声明一个 code 类型的变量即可。
lua可以使用所有的jass native函数。不过遗憾的是jass本身就没有直接调用code的native函数，你只能通过trigger或boolexper等方式变相调用。

**Comment by bamboo98** [comment]
那我现在思路大概是这样...
jass里整个0.01秒的计时器,监测一个普通的全局变量
lua通过给全局变量赋值来告诉jass需要运行哪个native函数以及传入的参数,应该是可行的?

**Comment by sumneko** [comment]
native函数直接用lua运行即可

**Comment by bamboo98** [comment]
唔姆...好像不算naive.....我是想调用DzAPI的

**Comment by sumneko** [comment]
lua也可以调用正确注册的japi函数，参考文档。

**Comment by bamboo98** [comment]
但是问题是dzapi根本就不在lua库里啊...想调用只能找其他办法吧

**Comment by sumneko** [comment]
请参考文档：https://github.com/actboy168/jass2lua/blob/master/lua-engine.md#jassjapi

**Comment by bamboo98** [comment]
卧槽,抱歉...我犯蠢了...打扰了
