### ISSUE TITLE
关于语言转换的思路

### ISSUE THREAD

**Issue by MeDeity** [actboy168/jass2lua#6]
你好,我想问下使用其他语言生成jass脚本的思路，比如使用C、java等语言来生成jass脚本。不知道大神有没有什么思路可以指点下

**Comment by sumneko** [comment]
如果你指的是把java代码转换成对应的jass代码的话，一般来说流程如下：
1. 解析 java 的语法树 JavaAst
2. 将 JavaAst 转换为 jassAst (比如处理符号优先级等）
3. 生成 jassAst 对应的 jass 代码

**Comment by MeDeity** [comment]
谢谢大佬解惑 @sumneko
